### PR TITLE
Edit link typo in readme.txt

### PR DESCRIPTION
**Pull request by SavPhill**
Edited a typo in the Github link title and changed the ordered list to ascending numbers

### CODE REVIEW

**Comment by bacoords** [comment]
I'm actually a fan of sticking to the current ordered list method in markdown files (1. 1. 1. 1. etc) because it makes it much easier to add/move new items without having to manually renumber. It also make visual diffs a lot cleaner.

Not sure what best practices are here, though.

**Comment by Sephsekla** [comment]
I'm in agreement on the list items. Markdown makes it unnecessary to worry about the numbers, so why add that worry back?

**Comment by bacoords** [comment]
The other fixes were just merged in #79 , so I vote to close this, but would encourage @SavPhill to contribute again!

**Comment by Sephsekla** [comment]
Agreed, it's really great to see someone new get stuck in!

**Comment by erikyo** [comment]
closing in favor of https://github.com/WordPress/wp-feature-notifications/pull/79

**Pull request closed without merging**
