### PR TITLE
chore: update `@wordpress/scripts`

### PR DESCRIPTION
**Pull request by johnhooks**
## What?

Update `@wordpress/scripts` to latest, `v26.1.0`.

## Why?

Trying to diagnosis Issue in the ESLint configuration discovered in PR #213.

### CODE REVIEW

**Review by erikyo — APPROVED** [review]
LGTM 🎉

**Review by erikyo — DISMISSED** [review]

**Comment by johnhooks** [comment]
@erikyo this doesn't fix the issue yet. We'll merge it in once we actually discover the problem.

**Comment by johnhooks** [comment]
I do think all the additions of this PR at the moment are a good idea, but they don't fix the Prettier ESLint reporting.

**Comment by erikyo** [comment]
> @erikyo this doesn't fix the issue yet. We'll merge it in once we actually discover the problem.

@johnhooks this is fixing also some issues that i got merging the storybook PR, since are package related

**Comment by johnhooks** [comment]
@erikyo do we want to merge it in? And I'll keep looking and make another PR when I find it?

I moved a lot of information about this to Issue #220.

If you want to merge, go ahead and we will keep looking.

**Comment by erikyo** [comment]
@johnhooks I'll try to do cherry picking from this in the meantime and if I can if you think it's not ready to be merged yet, but ideally it's okay for me since it's updating old packages. 

Only one thing... there would be no need to add packages like "@wordpress/eslint-plugin" because they are already bundled with wp-scripts, check this 
https://github.com/WordPress/performance/pull/468#discussion_r1024658920

**Comment by johnhooks** [comment]
@erikyo It was mostly a Hail Mary attempt, I can remove

**Comment by erikyo** [comment]
Yes, if it is possible, we should only add packages that are not already available, so we avoid having to maintain them and we are sure they are the "right ones"

https://github.com/WordPress/gutenberg/blob/641949ab72f65e617d3bf69cb71568cfe6799188/packages/scripts/package.json#L60-76

**Review by erikyo — APPROVED** [review]

**Review by erikyo — APPROVED** [review]

**Pull request merged**
