### PR TITLE
refactor: move to TypeScript and restructure src directory

### PR DESCRIPTION
**Pull request by johnhooks**
## What?

- Switch to TypeScript
- Restructure the src directory to put components into separate directories.
- ~Move css related to components to their individual directories.~

## Why?

TypeScript is great and so is organization.

### CODE REVIEW

**Comment by Sephsekla** [comment]
Awesome stuff! I've only scanned this but this is a massive improvement.

**Comment by johnhooks** [comment]
@Sephsekla thanks, I still need to break the css apart and put the styles directly next to the components.

**Comment by johnhooks** [comment]
@Sephsekla @erikyo I'm going to walk back the attempt to split out the styling. I'm going to fix this PR to be just about the JS to TS conversion.

**Review by erikyo — APPROVED** [review]
LGTM! 
(a PR will follow to fix the storybook setup)

**Pull request merged**
