### PR TITLE
feature: mvp

### LINKED ISSUE #302: Minimum Viable Product - v0.3.0
To facilitate a fast feedback loop, the project needs to provide a true to life preview of the notification system. It needs to be a functional system with a focus on the minimum features required to do the following:

## MVP

- [x] #304

- Notifications REST API - Basic **CRUD** actions

   - [ ] #303
   - [ ]  #307
   - [ ] #176
  

   **D**elete a notification - This may not be necessary initially. The dismiss action is most important.

- Client

   - [x] The current user's notifications are displayed on page load.
   - [ ] #306
   - [ ] #305

- Seeding test data

   - [ ] #200

## To implement in a later iteration

- User configurable channel subscriptions. All users will receive all notifications in the MVP.
- Emit a notification from the client to persist in the database.

### PR DESCRIPTION
**Pull request by johnhooks**
## What?

Create a minimum viable product of the notification plugin.

## Why?

There is still a lot to learn, but we need a minimally functional system to explore the possiblities.

## How?

Combines PRs:

- #178 
- #298 
- #204 
- #214  
- #291
- #255 
- #256 

## Necessary functionality for MVP*

- [x] Activate
- [x] Uninstall
- [ ] Classes
   - [x] Channel
   - [x] Channel_Registry
   - [x] Message
   - [x] Message_Factory
   - [x] Notice
   - [x] Notice_Factory
   - [x] Subscription 
   - [x] Subscription_Factory
- [ ] Database
  - [x] Messages table
  - [x] Queue table
  - [x] Subscriptions table
  - [x] Message_Repository
  - [ ] Notice_Repository (the queue table)
  - [x] Subscription_Repository
- [ ] REST API
  - [ ] `Notification_Controller` `wp-notifications/v1/notifications`
    - [x] `GET /notifications/`
    - [ ] `GET /notifications/{id}`
    - [ ] `POST /notifications/{id}`
    - [ ] `PUT /notifications /{id}`
    - [ ] `DELETE  /notifications /{id}`
  - [ ] `Subscription_Controller` `wp-notifications/v1/subscriptions` 
    - [ ] `GET /subscriptions/`
    - [ ] `GET /subscriptions/{id}`
    - [ ] `POST /subscriptions/{id}`
    - [ ] `PUT /subscriptions /{id}`
    - [ ] `DELETE  /subscriptions /{id}`
- [ ] CLI Command
  - [x] Seed users
  - [x] Seed subscriptions
  - [ ] Seed notification messages
  - [x] List registered channels 
  - [ ] List user's notifications
  - [ ] List user's subscriptions

* Only a rough outline right now, and heavily concentrated on the backend.

### CODE REVIEW

**Comment by Sephsekla** [comment]
This is looking phenomenal already, thanks for the hard work here!

**Comment by johnhooks** [comment]
@Sephsekla thanks, it feels like its coming a long well. Right now I'm going for simple, a lot will need adjusting to make the rest api function the way I would expect. Right now I don't have the right features in the models/factories/repositories for supporting `_embed` or `_fields` parameters in the rest api. But I am saving optimization and streamlining for later. For right now, we really just need to basic CRUD actions to get off the ground.

**Comment by Sephsekla** [comment]
@johnhooks when you have a sec, do you mind having a look at these merge conflicts? I'd like to try and get this rolling again by splitting out some of the remaining work (and possibly merging this one to development as is), but I'm not sure how to reslve things.

**Comment by johnhooks** [comment]
@Sephsekla this branch should actually be closed, all of the features of this branch have already been merged in. I brought all of this into `develop` through smaller PRs.

**Pull request closed without merging**
