### PR TITLE
Fix JavaScript linting issues

### PR DESCRIPTION
**Pull request by erikyo**
## What?
As @johnhooks reported, there have been problems with linting that need to be resolved, perhaps due to some updates that have been made to the [eslint rules](https://www.npmjs.com/package/@wordpress/eslint-plugin) over time. 

## Why?
Will close this issue Fix JavaScript linting issues #208

### CODE REVIEW

**Review by johnhooks — APPROVED** [review]
LGTM, it cleans up all the lint errors.

**Review by johnhooks — APPROVED** [review]

**Review by johnhooks — APPROVED** [review]

**Review by Sephsekla — APPROVED** [review]
🚀

**Comment by erikyo** [comment]
@Sephsekla could you please approve this one? Unfortunately, it doesn't need to be approved before I sync the pr with the repo, it has to be done later or we are forced to do it in two steps

**Review by Sephsekla — APPROVED** [review]

**Comment by johnhooks** [comment]
@erikyo What changed between merging this branch and the ESLint issue? There wasn't a problem with the `lint:js` script at this point in the history?

**Pull request merged**
