### PR TITLE
feature: add PSR-4 autoloading

### PR DESCRIPTION
**Pull request by johnhooks**
## What?

Add PSR-4 autoloading. Begins work on #4.

## How?

Modifies the `composer.json` with autoloading paths and namespaces the require `vendor/autoload.php` in `wp-feature-notifications.php`

Blocked until #197 is resolved.

### CODE REVIEW

**Comment by johnhooks** [comment]
@erikyo does part of the vendor folder have to be checked in to do this?

**Comment by johnhooks** [comment]
This will require a change to the JS CI workflow. There needs to be a composer install step to generate the autoloading functions. We can either add composer to the JS workflow or use a build asset of the plugin zip in the JS environment, which
would include the vendor folder and autoloading files.

**Comment by erikyo** [comment]
https://github.com/WordPress/wp-feature-notifications/actions/runs/4585697787/jobs/8097988162?pr=201

☝️ This is strange since husky has to perform [repo wide php linting ](https://github.com/WordPress/wp-feature-notifications/blob/b09e7b34d83b213a10b1c6d871761257e36dd26d/.husky/pre-commit#L4)

**Comment by johnhooks** [comment]
@erikyo it was because the prepare script wasn't added yet and I hadn't run "husky install".

**Comment by johnhooks** [comment]
Don't filenames have to match the class names for PSR-4 autoloading to work?

https://www.php-fig.org/psr/psr-4/#3-examples

@Sephsekla are we willing to change this lint rule so we can use PSR-4 autoloading?

**Comment by johnhooks** [comment]
Not implementing PSR-4 autoloading to maintain WP coding standards.

**Pull request closed without merging**
